version: "3.9"

services:
  frontend:
    build: .
    ports: 
      - "80:80"
    depends_on:
      - database
    networks:
      - main-net
  database:
    image: arm64v8/mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    networks:
      - main-net
  backend:
    build: bank-transfer-api
    ports: 
      - "8081:8081"
    depends_on:
      - frontend
    networks:
      - main-net   
networks:
  main-net:
